version: "2.4"
services:
  mssql:
    build:
      context: ../xc-common/mssql/common
      dockerfile: ../standalone/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-mssql:${XP_SITECORE_TAG}
        SITECORE_CORE_DB: ${SITECORE_CORE_DB}
    image: sitecore-xc0-mssql
  solr:
    build:
      context: ../xc-common/solr
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-solr:${XP_SITECORE_TAG}
        SOLR_COMMERCE_CORE_NAMES: "CatalogItems,Customers,Orders,PriceCards,Promotions"
    image: sitecore-xc0-solr
  cm:
    build:
      context: ./cm
      dockerfile: ../../xc-common/cd-cm/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${XP_SITECORE_TAG}
    image: sitecore-xc0-cm
  xconnect:
    build:
      context: ./xconnect
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-xconnect:${XP_SITECORE_TAG}
    image: sitecore-xc0-xconnect
  xdbsearchworker:
    build:
      context: ../xc-common/xdbworkers
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbsearchworker:${XP_SITECORE_TAG}
        CONTENT_PATH: xdbsearchworker/wdp/App_Data/jobs/continuous/IndexWorker
    image: sitecore-xc0-xdbsearchworker
  xdbautomationworker:
    build:
      context: ../xc-common/xdbworkers
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp0-xdbautomationworker:${XP_SITECORE_TAG}
        CONTENT_PATH: xdbautomationworker/wdp/App_Data/jobs/continuous/AutomationEngine
    image: sitecore-xc0-xdbautomationworker
