apiVersion: v1
kind: Service
metadata:
  name: smtp
  labels:
    {{- include "smtp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.smtp }}
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "smtp.selectorLabels" . | nindent 4 }}
