version: "2.4"
services:
  cd:
    image: sitecore-def-${TOPOLOGY}-cd:${SITECORE_VERSION}
  cm:
    image: sitecore-def-${TOPOLOGY}-cm:${SITECORE_VERSION}
  id:
    image: sitecore-def-${TOPOLOGY}-id:${SITECORE_VERSION}
  mssql:
    image: sitecore-def-${TOPOLOGY}-mssql:${SITECORE_VERSION}