services:  
  mssql-init:
    image: sitecore-xc1-mssql-init
    build:
      isolation: ${ISOLATION}
      context: ./mssql/init
      args:
        BASE_IMAGE: xc1-mssql-init:latest
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-spe-assets:${SPE_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-storefront-assets:${XC_PACKAGES_TAG}
  solr-init:
    image: sitecore-xc1-solr-init
    build:
      isolation: ${ISOLATION}
      context: ./solr-init
      args:
        BASE_IMAGE: xc1-solr-init:latest
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-sxa-xp1-assets:${SXA_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-storefront-assets:${XC_PACKAGES_TAG}
  solr-init-searchstax:
    image: sitecore-xc1-solr-init-searchstax
    build:
      isolation: ${ISOLATION}
      context: ./solr-init
      args:
        BASE_IMAGE: xc1-solr-init-searchstax:latest
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-sxa-xp1-assets:${SXA_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-storefront-assets:${XC_PACKAGES_TAG}
  cd:
    image: sitecore-xc1-cd
    build:
      isolation: ${ISOLATION}
      context: ./cd
      args:
        BASE_IMAGE: xc1-cd:latest
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-sxa-xp1-assets:${SXA_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-storefront-assets:${XC_PACKAGES_TAG}              
  cm:
    image: sitecore-xc1-cm
    build:
      isolation: ${ISOLATION}
      context: ./cm
      args:
        BASE_IMAGE: xc1-cm:latest
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-spe-assets:${SPE_SITECORE_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sitecore-sxa-xp1-assets:${SXA_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc1-storefront-assets:${XC_PACKAGES_TAG}               