image: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

resources:
  limits:
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 2048Mi

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}