apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
spec:
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cm
        env:
        - name: Sitecore_ConnectionStrings_ExperienceEdge
          valueFrom:
            secretKeyRef:
              name: sitecore-experienceedge
              key: sitecore-experienceedge-connection.txt
        - name: Sitecore_ExperienceEdge_DeliveryEndpoint_CircuitBreakerAttemptsBeforeBreak
          value: "12"
        - name: Sitecore_ExperienceEdge_DeliveryEndpoint_CircuitBreakerDurationOfBreak
          value: "00:15:00"
        - name: Sitecore_ExperienceEdge_DeliveryEndpoint_TransientFailureRetryCount
          value: "3"
        - name: Sitecore_ExperienceEdge_DeliveryEndpoint_TransientFailureSleepTime
          value: "00:00:10"
        - name: Sitecore_ExperienceEdge_EnableItemLanguageFallback
          value: "false"
        - name: Sitecore_ExperienceEdge_EnableFieldLanguageFallback
          value: "false"
        - name: Sitecore_ExperienceEdge_MaxExportEntitiesThreadCount
          value: "20"
        - name: Sitecore_ExperienceEdge_MaxPublishThreadCount
          value: "2"
        - name: Sitecore_ExperienceEdge_ExportEntitiesBufferSize
          value: "500"
        - name: Sitecore_ExperienceEdge_ExportPublishEventsBatchSize
          value: "150"        
        - name: Sitecore_ExperienceEdge_LayoutService_ConfigName
          value: "default"        
        - name: Sitecore_ExperienceEdge_MaxMetadataCacheSize
          value: "30MB"
        - name: Sitecore_ExperienceEdge_CheckDeltaStatusBatchSize
          value: "250"
        - name: Sitecore_ExperienceEdge_AckCleanupTimeoutSeconds
          value: "5"
        - name: Sitecore_ExperienceEdge_AckBatchWaitTimeoutSeconds
          value: "120"
        - name: Sitecore_ExperienceEdge_AckWaitTimeoutSeconds
          value: "600"
        - name: Sitecore_ExperienceEdge_MaxDependencyResolutionThreadCount
          value: "5"
