apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
spec:
  rules:
  - host: "{{ .Values.global.sitecore.tenantservice.host }}"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
              name: tenantservice
              port: 
                number: 80
  tls:
  - secretName: global-ts-tls
    hosts:
    - "{{ .Values.global.sitecore.tenantservice.host }}"
