apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../xm1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: sitecore-chub-connection-strings
  files:
    - sitecore-cmp-service-bus-entity-path-in.txt
    - sitecore-cmp-service-bus-subscription.txt
    - sitecore-cmp-service-bus-entity-path-out.txt
    - sitecore-cmp-content-hub.txt
    - sitecore-dam-content-hub.txt
    - sitecore-dam-search-page.txt
    - sitecore-dam-external-redirect-key.txt