apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/ingress-nginx

patchesJson6902:
  - path: patch-ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: sitecore-ingress
      version: v1

