apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sitecore-horizon
  newName: scr.sitecore.com/sxp/modules/sitecore-horizon
  newTag: 2.26-ltsc2019
  
resources:
  - hrz.yaml