services:
  cm:
    image: sitecore-sfmcbde-xp1-cm:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_sfmc: ${ConnectionString_sfmc}
      Sitecore_ConnectionStrings_TenantService: ${ConnectionString_TS}
  id:
    image: sitecore-sfmcbde-id:${SITECORE_VERSION}
  xdbautomationworker:
    image: sitecore-sfmcbde-xp1-xdbautomationworker:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_TenantService: ${ConnectionString_TS}
  xdbsearchworker:
    image: sitecore-sfmcbde-xp1-xdbsearchworker:${SITECORE_VERSION}
  xdbsearch:
    image: sitecore-sfmcbde-xp1-xdbsearch:${SITECORE_VERSION}
  xdbcollection:
    image: sitecore-sfmcbde-xp1-xdbcollection:${SITECORE_VERSION}
  cd:
    image: sitecore-sfmcbde-xp1-cd:${SITECORE_VERSION}
