version: "2.4"
services:
  cm:
    image: sitecore-sfcrm-xp0-cm:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_mysf: ${MYSF_CONNECTIONSTRING}
  mssql:
    image: sitecore-sfcrm-xp0-mssql:${SITECORE_VERSION}
  xdbsearchworker:
    image: sitecore-sfcrm-xp0-xdbsearchworker:${SITECORE_VERSION}
  xconnect:
    image: sitecore-sfcrm-xp0-xconnect:${SITECORE_VERSION}
