apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../xp1

images:
- name: sitecore-xp1-cm
  newName: "{registry}/sitecore-def-xp1-cm"
  newTag: tag
- name: sitecore-xp1-cd
  newName: "{registry}/sitecore-def-xp1-cd"
  newTag: tag
- name: sitecore-id
  newName: "{registry}/sitecore-def-xp1-id"
  newTag: tag
- name: sitecore-xp1-xdbautomationworker
  newName: "{registry}/sitecore-def-xp1-xdbautomationworker"
  newTag: tag
  
patchesStrategicMerge:
- patch-cm.yaml