---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: engine-env
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: engine-env
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: engine-env
  resources:
    requests:
      storage: 1Gi