---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mssql-data
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: mssql-data
  resources:
    requests:
      storage: 10Gi