apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../xp1
  - ../../dds
images:
- name: scr.sitecore.com/sxp/sitecore-xp1-cm
  newName: "{registry}/sitecore-dds-xp1-cm"
  newTag: tag
  

patchesStrategicMerge:
- patch-cm.yaml