apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
spec:
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cm
        env:
        - name: Sitecore_ConnectionStrings_EXM.AuthenticationKey 
          valueFrom:
            secretKeyRef:
              name: exm
              key: sitecore-exm-authentication-key.txt
        - name: Sitecore_ConnectionStrings_EXM.CryptographicKey
          valueFrom:
            secretKeyRef:
              name: exm
              key: sitecore-exm-cryptographic-key.txt
        - name: Sitecore_ConnectionStrings_EXM.InternalApiKey 
          valueFrom:
            secretKeyRef:
              name: exm
              key: sitecore-exm-internalapi-key.txt
        - name: Sitecore_EXM_DedicatedServer
          value: http://dds 
        - name: Sitecore_EXM_SMTP_Server
          value: "localhost"
        - name: Sitecore_EXM_SMTP_Port
          value: "25"
        - name: Sitecore_EXM_SMTP_UserName
          value: ""
        - name: Sitecore_EXM_SMTP_Password
          value: ""
        - name: Sitecore_EXM_SMTP_AuthenticationMethod
          value: "None"
        - name: Sitecore_EXM_SMTP_StartTls
          value: "false"
        - name: Sitecore_EXM_POP3_Server
          value: "localhost"
        - name: Sitecore_EXM_POP3_Port
          value: "110"
        - name: Sitecore_EXM_POP3_UserName
          value: ""
        - name: Sitecore_EXM_POP3_Password
          value: ""
        - name: Sitecore_EXM_POP3_UseSsl
          value: "false"
        - name: Sitecore_EXM_POP3_StartTls
          value: "false"                                    