apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: global-hrz-tls
  files:
    - tls/global-hrz/tls.key
    - tls/global-hrz/tls.crt
  type: kubernetes.io/tls


