image: solr:8.4.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8983

javaMem: "-Xms768M -Xmx768M"
solrHeap: "768M"
solrMode: "solrcloud"

resources:
  limits:
    memory: 1536Mi
  requests:
    cpu: 200m
    memory: 1536Mi

volumeClaim:
  storageClassName: ""
  storageSize: ""
  accessModes: []

livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
