apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../xm1/secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:  
- name: sitecore-experienceedge
  files:
  - sitecore-experienceedge-connection.txt

