apiVersion: v1
kind: Service
metadata:
  name: cdp
  labels:
    {{- include "cdp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cdp.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 80
