apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ..\..\..\init

patchesStrategicMerge:
  - solr-init.yaml

images:
- name: sitecore-xm1-solr-init-searchstax
  newName: ideftdevacr.azurecr.io/sxp/sitecore-xm1-solr-init-searchstax
  newTag: 10.4.0.010422.2299-10.0.17763.5820-ltsc2019

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-solr-searchstax
  files:
  - sitecore-searchstax-apikey.txt
  - sitecore-searchstax-account-name.txt
  - sitecore-searchstax-deployment-uid.txt
