apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: exm
  files:
    - sitecore-exm-authentication-key.txt
    - sitecore-exm-cryptographic-key.txt
    - sitecore-exm-internalapi-key.txt