apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: solr
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8983
        env:
        - name: SOLR_MODE
          value: solrcloud
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS 
          value: "true"
        volumeMounts:
          - name: data
            mountPath: "data"
      imagePullSecrets:
      - name: sitecore-docker-registry
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: solr