apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: scch-cmp-connection-strings
  files:
    - sitecore-cmp-service-bus-entity-path-in.txt
    - sitecore-cmp-service-bus-subscription.txt
    - sitecore-cmp-service-bus-entity-path-out.txt
    - sitecore-cmp-content-hub.txt
- name: scch-dam-connection-strings
  files:
    - sitecore-dam-content-hub.txt
    - sitecore-dam-search-page.txt
    - sitecore-dam-external-redirect-key.txt
