apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts
spec:
  selector:
    matchLabels:
      app: ts
  template:
    metadata:
      labels:
        app: ts
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-ts
        env:
        - name: TenantService_ConnectionStrings_xconnect.collection
          value: http://xdbcollection
        - name: TenantService_ConnectionStrings_Xdb.ReferenceData.Client
          value: http://xdbrefdata
        - name: TenantService_ConnectionStrings_sitecore
          valueFrom:
            secretKeyRef:
              name: sitecore-tenant-connection-strings
              key: sitecore-tenant-connection-string.txt
        - name: TenantService_ConnectionStrings_sfmc
          valueFrom:
            secretKeyRef:
              name: sitecore-salesforce-bde
              key: sitecore-salesforce-bde-connection-string.txt
        - name: TenantService_SfmcJourney_ExecuteUrl
          value: https://[ts-hostname]/api/tenantservice?id={{tenantserviceendpoint}}