version: "2.4"
services:
  id:
    isolation: ${ISOLATION}
    build:
      context: ./id
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-id6:${XP_SITECORE_TAG}
    image: sitecore-xc-id6
  bizfx:
    isolation: ${ISOLATION}
    build:
      context: ./bizfx
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/servercore/iis:windowsservercore-${OS_IMAGE_TAG_IIS}
    image: sitecore-xc-bizfx
  engine:
    isolation: ${ISOLATION}
    build:
      context: ./engine
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/servercore:${OS_IMAGE_TAG}
    image: sitecore-xc-engine
