image: scr.sitecore.com/sxp/sitecore-xp0-cm:10.2.0-ltsc2019

resources:
    limits:
      memory: 5Gi
    requests:
      cpu: 1
      memory: 5Gi

env: {}

global:
  orderCloud:
    buyerClientId: ""
    baseApiUrl: ""
