apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../k8s-sitecore-xp1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: tenant-service-xdbreferencedata-client
  files:
    - tenant-service-xdbreferencedata-client.txt
- name: tenant-service-sfmcjourney-executeurl
  files:
    - tenant-service-sfmcjourney-executeurl.txt
- name: sitecore-tenant-service-connection
  files:
    - sitecore-tenant-service-connection-string.txt
