generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-solr-searchstax
  files:
  - sitecore-searchstax-apikey.txt
  - sitecore-searchstax-account-name.txt
  - sitecore-searchstax-deployment-uid.txt