apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../k8s-sitecore-xp1/init

images:
- name: ideftdevacr.azurecr.io/sxp/sitecore-xp1-mssql-init
  newName: "ideftdevacr.azurecr.io/experimental/sfcrm/sitecore-xp1-mssql-init"
  newTag: sc101sfcrm6