version: "2.4"
services:
  cm:
    image: sitecore-sfcrm-xp1-cm:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_mysf: ${MYSF_Connectionstring}
  mssql:
    image: sitecore-sfcrm-xp1-mssql:${SITECORE_VERSION}
  xdbsearchworker:
    image: sitecore-sfcrm-xp1-xdbsearchworker:${SITECORE_VERSION}
  xdbsearch:
    image: sitecore-sfcrm-xp1-xdbsearch:${SITECORE_VERSION}
  xdbcollection:
    image: sitecore-sfcrm-xp1-xdbcollection:${SITECORE_VERSION}
