services:
  cd:
    image: sitecore-def-${TOPOLOGY}-cd:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_TenantService: https://${TENANT_SERVICE_HOST}
  cm:
    image: sitecore-def-${TOPOLOGY}-cm:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_TenantService: https://${TENANT_SERVICE_HOST}
  id:
    image: sitecore-def-${TOPOLOGY}-id:${SITECORE_VERSION}
  xdbautomationworker:
    image: sitecore-def-${TOPOLOGY}-xdbautomationworker:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_TenantService: https://${TENANT_SERVICE_HOST}