<<<<<<< Updated upstream
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: mssql
        image: {registry}/{nonproduction-project}/mssql-developer:2017-{short-version-ltsc}
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-databasepassword.txt
        - name: ACCEPT_EULA
          value: "Y"
      imagePullSecrets:
=======
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: mssql
        image: {registry}/{nonproduction-project}/mssql-developer:2017-{short-version-ltsc}
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sitecore-database
              key: sitecore-databasepassword.txt
        - name: ACCEPT_EULA
          value: "Y"
      imagePullSecrets:
>>>>>>> Stashed changes
      - name: sitecore-docker-registry