<<<<<<< Updated upstream
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-redis
        image: {registry}/{project}/sitecore-redis:{version}
        ports:
        - containerPort: 6379
      imagePullSecrets:
=======
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-redis
        image: {registry}/{project}/sitecore-redis:{version}
        ports:
        - containerPort: 6379
      imagePullSecrets:
>>>>>>> Stashed changes
      - name: sitecore-docker-registry