<<<<<<<< HEAD:demo/10.1/platform-xp0/charts/ps/values.yaml
replicaCount: 1

image:

pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  
  create: true
  
  annotations: {}
  
  name:

podSecurityContext: {}


securityContext: {}


service:
  type: ClusterIP
  port: 80

cmServiceNameOverride: ""
sqlServiceNameOverride: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []
 
resources: 
  limits:
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 1024Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 60

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 60

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}
========
replicaCount: 1

image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:

  create: true

  annotations: {}

  name:

podSecurityContext: {}


securityContext: {}


service:
  type: ClusterIP
  port: 80

solrServiceNameOverride: ""
sqlServiceNameOverride: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []

  tls: []


resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 60

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 60

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}
>>>>>>>> github.com/master:demo/9.3/sitecore-demo-platform/charts/automationengine/values.yaml
