apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      imagePullSecrets:
        - name: sitecore-docker-registry
      containers:
      - name: solr-init
        image: scr.sitecore.com/sxp/sitecore-xm1-solr-init-searchstax:10.0-ltsc2019
        env:
        - name: SITECORE_SOLR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-connection-string.txt
        - name: SOLR_CORE_PREFIX_NAME
          valueFrom:
            secretKeyRef:
              name: sitecore-solr
              key: sitecore-solr-core-prefix-name.txt
        - name: SEARCH_STAX_APIKEY
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-searchstax
              key: sitecore-searchstax-apikey.txt
        - name: SEARCH_STAX_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-searchstax
              key: sitecore-searchstax-account-name.txt
        - name: SEARCH_STAX_DEPLOYMENT_UID
          valueFrom:
            secretKeyRef:
              name: sitecore-solr-searchstax
              key: sitecore-searchstax-deployment-uid.txt
      restartPolicy: Never
  backoffLimit: 5