apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../xp1
- ../../sps

images:
- name: scr.sitecore.com/sxp/sitecore-xp1-cm
  newName: "{registry}/sitecore-sps-integration-xp1-cm"
  newTag: tag
- name: scr.sitecore.com/sxp/sitecore-xp1-cd
  newName: "{registry}/sitecore-sps-integration-xp1-cd"
  newTag: tag

patchesStrategicMerge:
- patch-cm.sps.yaml
