apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../xp1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: tenant-service-sitecore-connection
  files:
    - tenant-service-sitecore-connection.txt
- name: tenant-service-xconnect-collection
  files:
    - tenant-service-xconnect-collection.txt
- name: global-ts-tls
  files:
    - tls/global-ts/tls.key
    - tls/global-ts/tls.crt
  type: kubernetes.io/tls
