image: sitecoredemocontainers.azurecr.io/lighthouse-mssql:10.0.0-latest-linux
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumeClaim:
  storageClassName: "managed-premium"
  storageSize: "5Gi"
  accessModes: 
    - ReadWriteOnce

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1433

edition: Express
sqlSaPassword:

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 2Gi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}

env: {}