version: "2.4"
services:
  cm:
    image: sitecore-experience-edge-connector-${TOPOLOGY}-cm:${VERSION}
    environment:
      Sitecore_ConnectionStrings_ExperienceEdge: "${XE_CONNECTION}"
      Sitecore_ExperienceEdge_DeliveryEndpoint_CircuitBreakerAttemptsBeforeBreak: "12"
      Sitecore_ExperienceEdge_DeliveryEndpoint_CircuitBreakerDurationOfBreak: "00:15:00"
      Sitecore_ExperienceEdge_DeliveryEndpoint_TransientFailureRetryCount: "3"
      Sitecore_ExperienceEdge_DeliveryEndpoint_TransientFailureSleepTime: "00:00:10"
      Sitecore_ExperienceEdge_EnableItemLanguageFallback: "false"
      Sitecore_ExperienceEdge_EnableFieldLanguageFallback: "false"
      Sitecore_ExperienceEdge_MaxExportEntitiesThreadCount: "20"
      Sitecore_ExperienceEdge_MaxPublishThreadCount: "2"
      Sitecore_ExperienceEdge_ExportEntitiesBufferSize: "500"
      Sitecore_ExperienceEdge_ExportPublishEventsBatchSize: "150"
      Sitecore_ExperienceEdge_LayoutService_ConfigName: "default"
      Sitecore_ExperienceEdge_MaxMetadataCacheSize: "100000"
      Sitecore_ExperienceEdge_CheckDeltaStatusBatchSize: "250"
      Sitecore_ExperienceEdge_AckCleanupTimeoutSeconds: "5"
      Sitecore_ExperienceEdge_AckWaitTimeoutSeconds: "600"
      Sitecore_ExperienceEdge_MaxDependencyResolutionThreadCount: "5"
