apiVersion: apps/v1
kind: Deployment
metadata:
  name: initcontainer
  labels:
    {{- include "initcontainer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "initcontainer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "initcontainer.selectorLabels" . | nindent 8 }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "initcontainer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: Database_Server
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databaseservername.txt
            - name: Database_Username
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databaseusername.txt
            - name: Database_Password
              valueFrom:
                secretKeyRef:
                  name: sitecore-database
                  key: sitecore-databasepassword.txt
            - name: HOST_CM
              value: "http://cm.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_CD
              value: "http://cd.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_PS
              value: "http://ps.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_ID
              value: "http://id.{{ .Release.Namespace }}.svc.cluster.local"
            - name: ADMIN_USER_NAME
              value: "{{ .Values.admin.username }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.admin.password }}"
            - name: MARKETING_DEFINITIONS_APIKEY
              value: DF7D20E837254C6FBFA2B854C295CB61
            - name: DAM_URL
              value: "{{ .Values.dam.url }}"
            - name: INIT_CONTEXT
              value: Data Source=$(Database_Server);Initial Catalog=platform_init_ready;User ID=$(Database_Username);Password=$(Database_Password);
            - name: COVEO_ORGANIZATION_ID
              value: "{{ .Values.coveo.organizationId }}"
            - name: COVEO_REGION
              value: "{{ .Values.coveo.region }}"
            - name: COVEO_API_KEY
              value: "{{ .Values.coveo.apiKey }}"
            - name: COVEO_SEARCH_API_KEY
              value: "{{ .Values.coveo.searchApiKey }}"
            - name: COVEO_FARM_NAME
              value: "{{ .Values.coveo.farmName }}"
            - name: COVEO_ADMIN_USER_NAME
              value: "{{ .Values.coveo.admin.username }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-ps
          image: mcr.microsoft.com/powershell:lts-ubuntu-16.04
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 2 } until ($(try {(Test-Connection -TcpPort 80 ps) -eq $True } catch { $false }));"]
        - name: wait-xdbcollection
          image: mcr.microsoft.com/powershell:lts-ubuntu-16.04
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 3 } until ($(try {(iwr http://xconnect/healthz/ready).StatusCode -eq 200} catch { $false }));"]
        - name: wait-cm
          image: mcr.microsoft.com/powershell:lts-ubuntu-16.04
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 3 } until ($(try {(iwr http://cm/healthz/ready).StatusCode -eq 200} catch { $false }));"]
        - name: wait-cd
          image: mcr.microsoft.com/powershell:lts-ubuntu-16.04
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 3 } until ($(try {(iwr http://cd/healthz/ready).StatusCode -eq 200} catch { $false }));"]
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
