services:
  tenant-service:
    isolation: ${ISOLATION}
    image: sitecore-sfmcbde-tenant-service:${MODULE_VERSION}
    depends_on:
      id:
        condition: service_healthy
      cm:
        condition: service_healthy
    environment:
      TenantService_ConnectionStrings_sitecore: database=master;tenant id=${SITECORE_TENANT_ID};host=http://cm;timeout=20;auth endpoint=http://id/;client secret=${SITECORE_CLIENT_SECRET};client id=${SITECORE_CLIENT_ID}
      TenantService_ConnectionStrings_xconnect.collection: http://xconnect
      TenantService_ConnectionStrings_Xdb.ReferenceData.Client: http://xconnect
      TenantService_ConnectionStrings_sfmc: ${ConnectionString_sfmc}
      TenantService_SfmcJourney_ExecuteUrl: ${TENANT_SERVICE_CONFIG_EXECUTE_URL}
    healthcheck:
      test: ["CMD", "powershell", "-command", "C:/Healthchecks/Healthcheck.ps1"]
      timeout: 300s
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.force-STS-Header.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.force-STS-Header.headers.stsSeconds=31536000"
      - "traefik.http.routers.ts-secure.entrypoints=websecure"
      - "traefik.http.routers.ts-secure.rule=Host(`${TENANT_SERVICE_HOST}`)"
      - "traefik.http.routers.ts-secure.tls=true"
      - "traefik.http.routers.ts-secure.middlewares=force-STS-Header"
      - "traefik.http.services.ts.loadbalancer.server.port=80"
