apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: sitecore-hostnames
  files:
  - cd-hostname
  - cm-hostname
  - id-hostname
  - bizfx-hostname
  - engine-authoring-hostname
  - engine-minions-hostname
  - engine-shops-hostname

vars:
- name: cd-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[cd-hostname]
- name: cm-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[cm-hostname]
- name: id-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[id-hostname]
- name: bizfx-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[bizfx-hostname]
- name: engine-authoring-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[engine-authoring-hostname]
- name: engine-minions-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[engine-minions-hostname]
- name: engine-shops-hostname
  objref:
    kind: ConfigMap
    name: sitecore-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data[engine-shops-hostname]