apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sitecore-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
spec:
  rules:
  - host: cd.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cd
            port:
              number: 80
  - host: cm.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cm
            port:
              number: 80
  - host: id.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: id
            port:
              number: 80
  - host: bizfx.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bizfx
            port:
              number: 80
  - host: authoring.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: engine-authoring
            port:
              number: 5000
  - host: minions.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: engine-minions
            port:
              number: 5000
  - host: ops.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: engine-ops
            port:
              number: 5000
  - host: shops.globalhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: engine-shops
            port:
              number: 5000
  tls:
  - secretName: global-cd-tls
    hosts:
    - cd.globalhost
  - secretName: global-cm-tls
    hosts:
    - cm.globalhost
  - secretName: global-id-tls
    hosts:
    - id.globalhost
  - secretName: global-bizfx-tls
    hosts:
    - bizfx.globalhost
  - secretName: global-authoring-tls
    hosts:
    - authoring.globalhost
  - secretName: global-minions-tls
    hosts:
    - minions.globalhost
  - secretName: global-ops-tls
    hosts:
    - ops.globalhost
  - secretName: global-shops-tls
    hosts:
    - shops.globalhost