version: "3.7"
services:
  mssql:
    isolation: ${ISOLATION}
    image: sitecore-xc1-mssql
    build:
      context: ./mssql
      dockerfile: ./standalone/Dockerfile
      args:
        BASE_IMAGE: ${XC_NONPRODUCTION_SITECORE_DOCKER_REGISTRY}xc1-mssql:${XC_PACKAGES_TAG}
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}spe-assets:${SPE_SITECORE_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
  mssql-init:
    isolation: ${ISOLATION}
    image: sitecore-xc1-mssql-init
    build:
      context: ./mssql
      dockerfile: ./init/Dockerfile
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}xc1-mssql-init:${XC_PACKAGES_TAG}
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}spe-assets:${SPE_SITECORE_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
  solr:
    isolation: ${ISOLATION}
    image: sitecore-xc1-solr
    build:
      context: ./solr
      dockerfile: ./standalone/Dockerfile
      args:
        BASE_IMAGE: ${XC_NONPRODUCTION_SITECORE_DOCKER_REGISTRY}xc1-solr:${XC_PACKAGES_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
  solr-init:
    isolation: ${ISOLATION}
    image: sitecore-xc1-solr-init
    build:
      context: ./solr
      dockerfile: ./init/Dockerfile
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}xc1-solr-init:${XC_PACKAGES_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
  cd:
    isolation: ${ISOLATION}
    image: sitecore-xc1-cd
    build:
      context: ./cd
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}xc1-cd:${XC_PACKAGES_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}
  cm:
    isolation: ${ISOLATION}
    image: sitecore-xc1-cm
    build:
      context: ./cm
      args:
        BASE_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}xc1-cm:${XC_PACKAGES_TAG}
        SPE_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}spe-assets:${SPE_SITECORE_TAG}
        SXA_RESOURCES_IMAGE: ${MODULES_SITECORE_DOCKER_REGISTRY}sxa-xp1-assets:${SXA_SITECORE_TAG}