apiVersion: apps/v1
kind: Deployment
metadata:
  name: initcontainer
  labels:
    {{- include "initcontainer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "initcontainer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "initcontainer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "initcontainer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: HOST_CM
              value: "http://cm.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_CD
              value: "http://cd.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_PS
              value: "http://ps.{{ .Release.Namespace }}.svc.cluster.local"
            - name: HOST_ID
              value: "http://id.{{ .Release.Namespace }}.svc.cluster.local"
            - name: ADMIN_USER_NAME 
              value: "{{ .Values.admin.username }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.admin.password }}"
            - name: MARKETING_DEFINITIONS_APIKEY
              value: DF7D20E837254C6FBFA2B854C295CB61
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-ps
          image: mcr.microsoft.com/powershell:lts-ubuntu-16.04
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 2 } until ($(try {(Test-Connection -TcpPort 80 ps) -eq $True } catch { $false }));"]
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
