image: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector:
  kubernetes.io/os: windows

tolerations: []

affinity: {}

admin:
  username: ""
  password: ""
  
user:
  password: ""
