services:
  mssql-upgrade:
    image: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-upgrade:${SITECORE_VERSION}
    environment:
      Sitecore_ConnectionStrings_Core: Data Source=${SQL_SERVER};Initial Catalog=${SQL_DATABASE_PREFIX}.Core;User ID=${SQL_USERNAME};Password=${SQL_PASSWORD}
      Sitecore_ConnectionStrings_Master: Data Source=${SQL_SERVER};Initial Catalog=${SQL_DATABASE_PREFIX}.Master;User ID=${SQL_USERNAME};Password=${SQL_PASSWORD}
      Sitecore_ConnectionStrings_Web: Data Source=${SQL_SERVER};Initial Catalog=${SQL_DATABASE_PREFIX}.Web;User ID=${SQL_USERNAME};Password=${SQL_PASSWORD}
      Sitecore_ConnectionStrings_Experienceforms: Data Source=${SQL_SERVER};Initial Catalog=${SQL_DATABASE_PREFIX}.Experienceforms;User ID=${SQL_USERNAME};Password=${SQL_PASSWORD}
      Database_Upgrade_From_Version: ${DATABASE_UPGRADE_FROM_VERSION}
      Database_Upgrade_To_Version: ${DATABASE_UPGRADE_TO_VERSION}
      Sitecore_License: ${SITECORE_LICENSE}
    isolation: ${ISOLATION}