apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd
spec:
  selector:
    matchLabels:
      app: cd
  template:
    metadata:
      labels:
        app: cd
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cd
        env:
        - name: Sitecore_ConnectionStrings_tenantservice
          valueFrom:
            secretKeyRef:
              name: sitecore-tenant-service
              key: sitecore-tenant-service-connection-string.txt
