apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../k8s-sitecore-xp1

images:
- name: scr.sitecore.com/sxp/sitecore-xp1-xdbautomationworker
  newName: "{registry}/sitecore-sfmcbde-xp1-xdbautomationworker"
  newTag: tag
- name: scr.sitecore.com/sxp/modules/sitecore-tenant-service
  newName: "{registry}/sitecore-sfmcbde-tenant-service"
  newTag: tag
  
patchesStrategicMerge:
- patch-cm.yaml
- patch-xdbautomationworker.yaml
- patch-ts.yaml
