apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- configmaps
images:
- name: sitecore-xm1-cd
  newName: scr.sitecore.com/sxp/sitecore-xm1-cd
  newTag: 10.2-ltsc2019
- name: sitecore-xm1-cm
  newName: scr.sitecore.com/sxp/sitecore-xm1-cm
  newTag: 10.2-ltsc2019
- name: sitecore-xm1-id
  newName: scr.sitecore.com/sxp/sitecore-id6
  newTag: 10.2-ltsc2019
resources:
- cm.yaml
- cd.yaml
- id.yaml
