apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../xp1

images:
- name: sitecore-ts
  newName: scr.sitecore.com/sxp/sitecore-tenant-service
  newTag: 8.0.0-ltsc2019

resources:
- ts.yaml