services:
  id:
    build:
      isolation: ${ISOLATION}
      context: ./id
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-id6:${XP_SITECORE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc0-assets:${XC_PACKAGES_TAG}               
    image: sitecore-xc-id6
  bizfx:
    build:
      isolation: ${ISOLATION}
      context: ./bizfx
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/servercore/iis:windowsservercore-${OS_IMAGE_TAG_IIS}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc0-assets:${XC_PACKAGES_TAG}
    image: sitecore-xc-bizfx
  engine:
    build:
      isolation: ${ISOLATION}
      context: ./engine
      args:
        BASE_IMAGE: mcr.microsoft.com/windows/servercore:${OS_IMAGE_TAG}
        ASSETS_IMAGE: ${XC_SITECORE_DOCKER_REGISTRY}sitecore-xc0-assets:${XC_PACKAGES_TAG}
        XC_ENGINE_PORT: ${XC_ENGINE_PORT}
    image: sitecore-xc-engine
