apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../k8s-sitecore-xp1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: sitecore-salesforce-content-exchange
  files:
    - sitecore-salesforce-content-exchange-connection-string.txt