apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/secrets
  
generatorOptions:
  disableNameSuffixHash: true
  
secretGenerator:
- name: sitecore-tenant-service
  files:
    - sitecore-tenant-service-connection-string.txt
