apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../xp1/secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: sitecore-dcrm-connection-strings
  files:
  - sitecore-dcrm.txt
  - sitecore-data-exchange-staging.txt
