apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sitecore-sps
  newName: scr.sitecore.com/sxp/modules/sitecore-sps
  newTag: 7.0-ltsc2022

resources:
- sps.yaml

patchesStrategicMerge:
- patch-sps.yaml