apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init
spec:
  replicas: {{ .Values.replicaCount }}
  backoffLimit: 10
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          env:
            - name: "SITECORE_SOLR_CONNECTION_STRING"
              value: http://solr:8983/solr;solrCloud=true
            - name: SOLR_CORE_PREFIX_NAME
              value: sitecore
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      initContainers:
        - name: wait-for-solr
          image: mcr.microsoft.com/powershell:lts-nanoserver-1809
          command: ["pwsh", "-Command", "do { Start-Sleep -Seconds 3 } until ($(try {(iwr http://solr:8983/solr/admin/info/system).StatusCode -eq 200} catch { $false }));"]
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
