apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../xm1

images:
- name: scr.sitecore.com/sxp/sitecore-xm1-cd
  newName: "{registry}/sitecore-chub-xm1-cd"
  newTag: tag
- name: scr.sitecore.com/sxp/sitecore-xm1-cm
  newName: "{registry}/sitecore-chub-xm1-cm"
  newTag: tag

patchesStrategicMerge:
  - patch-cd.scch.yaml
  - patch-cm.scch.yaml
