apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
spec:
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cm
        env:
        - name: Sitecore_ConnectionStrings_sfmc
          valueFrom:
            secretKeyRef:
              name: sitecore-salesforce-bde
              key: sitecore-salesforce-bde-connection-string.txt
