{{- if .Values.ingress.enabled -}}
{{- $fullName := include "buyer.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "buyer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - secretName: global-buyer-tls
    hosts:
    - {{ .Values.global.sitecore.buyer.host | quote }}
  rules:
  - host: {{ .Values.global.sitecore.buyer.host | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: buyer
            port: 
              number: 80
{{- end }}
