image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8983

javaMem: "-Xms768M -Xmx768M"
solrHeap: "768M"

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 1Gi

volumeClaim:
  storageClassName: ""
  storageSize: ""
  accessModes: []

livenessProbe:
  initialDelaySeconds: 45
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
