generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: mssql-upgrade-config
  files:
  - configuration/sql-server.txt
  - configuration/sql-database-prefix.txt
  - configuration/database-upgrade-from-version.txt
  - configuration/database-upgrade-to-version.txt
secretGenerator:
- name: mssql-upgrade-secret
  files:
  - configuration/sql-user-name.txt
  - configuration/sql-password.txt
  - configuration/sitecore-license.txt
resources:
- mssql-upgrade.yaml
images:
- name: sitecore-xm1-mssql-upgrade
  newName: ideftdevacr.azurecr.io/sxp/sitecore-xm1-mssql-upgrade
  newTag: 10.4.0.010422.2299-10.0.17763.5820-ltsc2019-unstable