generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-admin
  files:
  - sitecore-adminpassword.txt
- name: sitecore-database
  files:
  - sitecore-databaseusername.txt
  - sitecore-databasepassword.txt
  - sitecore-databaseservername.txt
  - sitecore-database-elastic-pool-name.txt
  - sitecore-master-database-username.txt
  - sitecore-master-database-password.txt
  - sitecore-core-database-username.txt
  - sitecore-core-database-password.txt
  - sitecore-web-database-username.txt
  - sitecore-web-database-password.txt
  - sitecore-forms-database-username.txt
  - sitecore-forms-database-password.txt
  - sitecore-databaseprefix.txt
  - sitecore-custom-database-prefix-update-from.txt
- name: sitecore-identitycertificate
  files:
  - sitecore-identitycertificate.txt
  - sitecore-identitycertificatepassword.txt
- name: sitecore-license
  files:
  - sitecore-license.txt
- name: sitecore-graphql
  files:
  - sitecore-graphql-uploadmedia_encryptionkey.txt
- name: sitecore-identity
  files:
  - sitecore-identitysecret.txt
- name: sitecore-telerik
  files:
  - sitecore-telerikencryptionkey.txt
- name: sitecore-solr
  files:
  - sitecore-solr-connection-string.txt
  - sitecore-solr-core-prefix-name.txt
- name: sitecore-protect-media-requests
  files:
  - sitecore-media-request-protection-shared-secret.txt
- name: sitecore-log-level
  files:
  - sitecore-log-level-value.txt
- name: global-cd-tls
  files:
    - tls/global-cd/tls.key
    - tls/global-cd/tls.crt
  type: kubernetes.io/tls
- name: global-cm-tls
  files:
    - tls/global-cm/tls.key
    - tls/global-cm/tls.crt
  type: kubernetes.io/tls
- name: global-id-tls
  files:
    - tls/global-id/tls.key
    - tls/global-id/tls.crt
  type: kubernetes.io/tls
