generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-admin
  files:
  - xp/sitecore-adminpassword.txt
- name: sitecore-database
  files:
  - xp/sitecore-databaseusername.txt
  - xp/sitecore-databasepassword.txt
  - xp/sitecore-databaseservername.txt
  - xp/sitecore-collection-shardmapmanager-database-password.txt
  - xp/sitecore-collection-shardmapmanager-database-username.txt
  - xp/sitecore-core-database-password.txt
  - xp/sitecore-core-database-username.txt
  - xp/sitecore-exm-master-database-password.txt
  - xp/sitecore-exm-master-database-username.txt
  - xp/sitecore-forms-database-password.txt
  - xp/sitecore-forms-database-username.txt
  - xp/sitecore-marketing-automation-database-password.txt
  - xp/sitecore-marketing-automation-database-username.txt
  - xp/sitecore-master-database-password.txt
  - xp/sitecore-master-database-username.txt
  - xp/sitecore-messaging-database-password.txt
  - xp/sitecore-messaging-database-username.txt
  - xp/sitecore-processing-engine-storage-database-password.txt
  - xp/sitecore-processing-engine-storage-database-username.txt
  - xp/sitecore-processing-engine-tasks-database-password.txt
  - xp/sitecore-processing-engine-tasks-database-username.txt
  - xp/sitecore-processing-pools-database-password.txt
  - xp/sitecore-processing-pools-database-username.txt
  - xp/sitecore-processing-tasks-database-password.txt
  - xp/sitecore-processing-tasks-database-username.txt
  - xp/sitecore-reference-data-database-password.txt
  - xp/sitecore-reference-data-database-username.txt
  - xp/sitecore-reporting-database-password.txt
  - xp/sitecore-reporting-database-username.txt
  - xp/sitecore-web-database-password.txt
  - xp/sitecore-web-database-username.txt
  - xp/sitecore-database-elastic-pool-name.txt
- name: sitecore-identitycertificate
  files:
  - xp/sitecore-identitycertificate.txt
  - xp/sitecore-identitycertificatepassword.txt
- name: sitecore-license
  files:
  - xp/sitecore-license.txt
- name: sitecore-identity
  files:
  - xp/sitecore-identitysecret.txt
- name: sitecore-telerik
  files:
  - xp/sitecore-telerikencryptionkey.txt
- name: sitecore-reporting
  files:
  - xp/sitecore-reportingapikey.txt
- name: sitecore-redis
  files:
  - xp/sitecore-redis-connection-string.txt
- name: sitecore-solr
  files:
  - xp/sitecore-solr-connection-string.txt
- name: sitecore-solr-xdb
  files:
  - xp/sitecore-solr-connection-string-xdb.txt
- name: commerce-bizfx
  files:
  - xc/commerce-bizfx-currency.txt
  - xc/commerce-bizfx-language.txt
  - xc/commerce-bizfx-shopname.txt
- name: commerce-connect-client
  files:
  - xc/commerce-connect-clientid.txt
  - xc/commerce-connect-clientsecret.txt
- name: commerce-braintree
  files:
  - xc/commerce-engine-braintreeenvironment.txt
  - xc/commerce-engine-braintreemerchantid.txt
  - xc/commerce-engine-braintreepublickey.txt
  - xc/commerce-engine-braintreeprivatekey.txt
- name: commerce-redis
  files:
  - xc/commerce-redis-connection-string.txt
  - xc/commerce-connect-redis-connection-string.txt
- name: commerce-solr
  files:
  - xc/commerce-solr-connection-string.txt
- name: global-cd-tls
  files:
    - tls/global-cd/tls.key
    - tls/global-cd/tls.crt
  type: kubernetes.io/tls
- name: global-cm-tls
  files:
    - tls/global-cm/tls.key
    - tls/global-cm/tls.crt
  type: kubernetes.io/tls
- name: global-id-tls
  files:
    - tls/global-id/tls.key
    - tls/global-id/tls.crt
  type: kubernetes.io/tls
- name: global-bizfx-tls
  files:
    - tls/global-bizfx/tls.key
    - tls/global-bizfx/tls.crt
  type: kubernetes.io/tls
- name: global-authoring-tls
  files:
    - tls/global-authoring/tls.key
    - tls/global-authoring/tls.crt
  type: kubernetes.io/tls
- name: global-minions-tls
  files:
    - tls/global-minions/tls.key
    - tls/global-minions/tls.crt
  type: kubernetes.io/tls
- name: global-ops-tls
  files:
    - tls/global-ops/tls.key
    - tls/global-ops/tls.crt
  type: kubernetes.io/tls
- name: global-shops-tls
  files:
    - tls/global-shops/tls.key
    - tls/global-shops/tls.crt
  type: kubernetes.io/tls