image: scr.sitecore.com/sxp/sitecore-xp1-cd:10.0.0-ltsc2019

resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

env: {}

volumeClaim:
  storageClassName: "managed-premium"
  storageSize: "1Gi"
  accessModes: 
    - ReadWriteOnce