apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sitecore-xm1-mssql-init
  newName: scr.sitecore.com/sxp/sitecore-xm1-mssql-init
  newTag: 10.3-ltsc2022
- name: sitecore-xm1-solr-init
  newName: scr.sitecore.com/sxp/sitecore-xm1-solr-init
  newTag: 10.3-ltsc2022

resources:
  - mssql-init.yaml
  - solr-init.yaml