apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: sitecore-xc1-mssql-init
  newName: scr.sitecore.com/sxc/nonproduction/sitecore-xc1-mssql-init
  newTag: 10.2-ltsc2019
- name: sitecore-xc1-solr-init
  newName: scr.sitecore.com/sxc/nonproduction/sitecore-xc1-solr-init
  newTag: 10.2-ltsc2019

resources:
  - mssql-init.yaml
  - solr-init.yaml