version: "2.4"
services:
  mssql:
    build:
      context: ../xc-common/mssql/common
      dockerfile: ../standalone/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-mssql:${XP_SITECORE_TAG}
        SITECORE_CORE_DB: ${SITECORE_CORE_DB}
    image: xc1-mssql
  mssql-init:
    build:
      context: ../xc-common/mssql/common
      dockerfile: ../init/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-mssql-init:${XP_SITECORE_TAG}
        TOPOLOGY: xc1
    image: xc1-mssql-init
  solr:
    build:
      context: ../xc-common/solr
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-solr:${XP_SITECORE_TAG}
        SOLR_COMMERCE_CORE_NAMES: "CatalogItems,Customers,Orders,PriceCards,Promotions"
    image: xc1-solr
  solr-init:
    build:
      context: ../xc-common/solr-init
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-solr-init:${XP_SITECORE_TAG}
        XC_TOPOLOGY: xc1
        SOLR_XDB_SCHEMA_FILE: "/Content/Website/App_Data/solrcommands/schema.json"
    image: xc1-solr-init
  rep:
    build:
      context: ./prcrep
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-rep:${XP_SITECORE_TAG}
    image: sitecore-xc1-rep
  xdbcollection:
    build:
      context: ./xdbcollection
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-xdbcollection:${XP_SITECORE_TAG}
    image: sitecore-xc1-xdbcollection
  prc:
    build:
      context: ./prcrep
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-prc:${XP_SITECORE_TAG}
    image: sitecore-xc1-prc
  cm:
    build:
      context: ./cm
      dockerfile: ../../xc-common/cd-cm/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-cm:${XP_SITECORE_TAG}
    image: xc1-cm
  cd:
    build:
      context: ./cd
      dockerfile: ../../xc-common/cd-cm/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-cd:${XP_SITECORE_TAG}
    image: xc1-cd
  xdbsearch:
    build:
      context: ./xdbsearch
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-xdbsearch:${XP_SITECORE_TAG}
    image: sitecore-xc1-xdbsearch
  xdbsearchworker:
    build:
      context: ../xc-common/xdbworkers
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-xdbsearchworker:${XP_SITECORE_TAG}
        CONTENT_PATH: xdbsearchworker/wdp/App_Data/jobs/continuous/IndexWorker
    image: sitecore-xc1-xdbsearchworker
  xdbautomation:
    build:
      context: ./xdbautomation
      dockerfile: ../../xc-common/prc-rep-xdba-xdbc/Dockerfile
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-xdbautomation:${XP_SITECORE_TAG}
    image: sitecore-xc1-xdbautomation
  xdbautomationworker:
    build:
      context: ../xc-common/xdbworkers
      args:
        BASE_IMAGE: ${XP_SITECORE_DOCKER_REGISTRY}sitecore-xp1-xdbautomationworker:${XP_SITECORE_TAG}
        CONTENT_PATH: xdbautomationworker/wdp/App_Data/jobs/continuous/AutomationEngine
    image: sitecore-xc1-xdbautomationworker
