replicaCount: 1

image:
  tag:
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

solrServiceNameOverride: ""
xconnectServiceNameOverride: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 2Gi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 60

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 60
nodeSelector: 
  kubernetes.io/os: windows

tolerations: []

affinity: {}
