apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../k8s-sitecore-xm1/init

images:
- name: scr.sitecore.com/sxp/sitecore-xm1-mssql-init
  newName: "{registry}/sitecore-sfmcce-xm1-mssql-init"
  newTag: tag
