apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mssql
  newName: mcr.microsoft.com/mssql/server
  newTag: 2022-CU10-ubuntu-22.04
- name: redis
  newName: redis
  newTag: 4.0.14-alpine
- name: solr
  newName: solr
  newTag: 8.11.2

resources:
  - mssql.yaml
  - redis.yaml
  - solr.yaml