apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
spec:
  selector:
    matchLabels:
      app: cm
  template:
    metadata:
      labels:
        app: cm
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xp1-cm
        env:
        - name: Sitecore_ConnectionStrings_DCRM
          valueFrom:
            secretKeyRef:
              name: sitecore-dcrm-connection-strings
              key: sitecore-dcrm.txt
        - name: Sitecore_ConnectionStrings_Sitecore.DataExchange.Staging
          valueFrom:
            secretKeyRef:
              name: sitecore-dcrm-connection-strings
              key: sitecore-data-exchange-staging.txt