apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../xp1/secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:  
- name: sitecore-experienceedge
  files:
  - sitecore-experienceedge-authority.txt
  - sitecore-experienceedge-deliveryendpoint.txt
  - sitecore-experienceedge-cdnuri.txt
  - sitecore-experienceedge-cdnmediaprefix.txt

