apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cm.secretName" . }}
  labels:
    {{- include "cm.labels" . | nindent 4 }}
type: Opaque
data:
  unicorn_shared_secret:  {{ .Values.unicornSharedSecret | b64enc | quote }}
  admin_password: {{ .Values.adminPassword | b64enc | quote }}
