apiVersion: v1
kind: Service
metadata:
  name: bizfx
spec:
  selector:
    app: bizfx
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizfx
  labels:
    app: bizfx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizfx
  template:
    metadata:
      labels:
        app: bizfx
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xc-bizfx
        image: {registry}/{sxc-project}/sitecore-xc-bizfx:{commerce-version}
        ports:
        - containerPort: 80
        env:
        - name: sitecore_xc_bizfx_default_language
          valueFrom:
            secretKeyRef:
              name: commerce-bizfx
              key: commerce-bizfx-language.txt
        - name: sitecore_xc_bizfx_default_currency
          valueFrom:
            secretKeyRef:
              name: commerce-bizfx
              key: commerce-bizfx-currency.txt
        - name: sitecore_xc_bizfx_default_shopname
          valueFrom:
            secretKeyRef:
              name: commerce-bizfx
              key: commerce-bizfx-shopname.txt
        - name: sitecore_xc_bizfx_bizfx_url
          value: https://bizfx.globalhost
        - name: sitecore_xc_bizfx_authoring_url
          value: https://authoring.globalhost
        - name: sitecore_xc_bizfx_identity_server_url
          value: https://id.globalhost
        livenessProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10
      imagePullSecrets:
      - name: sitecore-docker-registry